import {TechnicalSkill} from '../models/technical-skill-model';

export const technicalSkills: TechnicalSkill[] = [
  { name: 'Java', knowledgeLevel: 1 },
  { name: 'Object-Oriented Programming (OOP)', knowledgeLevel: 1 },
  { name: 'Hibernate ORM', knowledgeLevel: 1 },
  { name: 'Spring Framework', knowledgeLevel: 1 },
  { name: 'Spring Security', knowledgeLevel: 1 },
  { name: 'OAuth', knowledgeLevel: 1 },
  { name: 'MySQL', knowledgeLevel: 1 },
  { name: 'Postgres', knowledgeLevel: 1 },
  { name: 'PostGIS', knowledgeLevel: 1 },
  { name: 'Web Technologies', knowledgeLevel: 1 },
  { name: 'HTML', knowledgeLevel: 1 },
  { name: 'CSS', knowledgeLevel: 1 },
  { name: 'JavaScript', knowledgeLevel: 1 },
  { name: 'TypeScript', knowledgeLevel: 1 },
  { name: 'Angular', knowledgeLevel: 1 },
  { name: 'React.js', knowledgeLevel: 1 },
  { name: 'Redux', knowledgeLevel: 1 },
  { name: 'Full-Stack Development', knowledgeLevel: 1 },
  { name: 'Software Design', knowledgeLevel: 1 },
  { name: 'Code Quality', knowledgeLevel: 1 },
  { name: 'Agile Methodologies', knowledgeLevel: 1 },
  { name: 'Research Methodology', knowledgeLevel: 1 },
  { name: 'Programming Teaching', knowledgeLevel: 1 },
  { name: 'Eclipse RCP', knowledgeLevel: 1 },
];

export const homeTechnicalSkills: TechnicalSkill[] = [
  { name: 'Java', knowledgeLevel: 1 },
  { name: 'OOP', knowledgeLevel: 1 },
  // { name: 'Hibernate ORM', knowledgeLevel: 1 },
  { name: 'Spring Framework', knowledgeLevel: 1 },
  // { name: 'Spring Security', knowledgeLevel: 1 },
  // { name: 'OAuth', knowledgeLevel: 1 },
  { name: 'MySQL', knowledgeLevel: 1 },
  // { name: 'Postgres', knowledgeLevel: 1 },
  // { name: 'PostGIS', knowledgeLevel: 1 },
  // { name: 'Web Technologies', knowledgeLevel: 1 },
  { name: 'HTML', knowledgeLevel: 1 },
  { name: 'CSS', knowledgeLevel: 1 },
  { name: 'JavaScript', knowledgeLevel: 1 },
  { name: 'TypeScript', knowledgeLevel: 1 },
  { name: 'Angular', knowledgeLevel: 1 },
  { name: 'React.js', knowledgeLevel: 1 },
  // { name: 'Redux', knowledgeLevel: 1 },
  // { name: 'Full-Stack Development', knowledgeLevel: 1 },
  { name: 'Software Design', knowledgeLevel: 1 },
  { name: 'Code Quality', knowledgeLevel: 1 },
  // { name: 'Agile Methodologies', knowledgeLevel: 1 },
  // { name: 'Research Methodology', knowledgeLevel: 1 },
  // { name: 'Programming Teaching', knowledgeLevel: 1 },
  // { name: 'Eclipse RCP', knowledgeLevel: 1 },
];

